### Pandas

Praticamente o excel do python  
essencial para manipular dados e analise de dados  
tentaremos entender tudo que da pra fazer com o pandas

In [5]:
import pandas as pd

Dataframes e Series

In [6]:
dados = {
    "Nome": ["joao", "keke", "epaminondas"],
    "Idade": [25, 33, 7],
}

df = pd.DataFrame(dados)
df

          Nome  Idade
0         joao     25
1         keke     33
2  epaminondas      7

In [7]:
## as series seriam como se fossem umas colunas

s = pd.Series([10, 20, 30])
s

0    10
1    20
2    30
dtype: int64

### Lendo um arquivo

pode ser csv ou qualquer outro

In [8]:
df = pd.read_excel('/home/felipe/Desktop/data_engineering_journey/data/producao-petroleo-b.xls')
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143,NaN,(n/d) = não disponível.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144,NaN,Dados atualizados em 30 de abril de 2026.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145,NaN,¹ Variação percentual do somatório dos valores...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
146,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147,NaN,Voltar ao índice,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Como esse arquivo que escolhi em especifico está no formato de relatório do excel e não uma tabela analítica, devemos fazer algumas alterações

In [9]:
raw = pd.read_excel("/home/felipe/Desktop/data_engineering_journey/data/producao-petroleo-b.xls", header=None)

print(raw.shape)
raw.head(40)

(149, 30)

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,Agência Nacional do Petróleo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,Superintendência de Defesa d...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,Produção Nacional de Petróleo e LGN (barris),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,Periodicidade: Mensal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,Índice:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,Produção nacional de petróleo por Unidade da F...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,Produção nacional de LGN por Unidade da Federa...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,Dados atualizados em 30 de abril de 2026.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,Produção nacional de petróleo por Unidade da F...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,"Selecione, clicando nas setas abaixo, a UNIDAD...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,BRASIL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,PETRÓLEO TOTAL (b),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,UN. DA FEDERAÇÃO,(Tudo),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,LOCALIZAÇÃO,(Tudo),NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,xxxxxxxxxxxxxxxxxx,xxxxxxxxxxxxxxxxx,xxxxxxxxxxxxxxxxx,xxxxxxxxxxxxxxxxx,xxxxxxxxxxxxxxxxx,xxxxxxxxxxxxxxxxx,xxxxxxxxxxxxxxxxx,xxxxxxxxxxxxxxxxx,xxxxxxxxxxxxxxxxx,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,ANO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,VARIAÇÃO DO ACUMULADO
31,NaN,Mês,2000,2001,2002,2003,2004,2005,2006,2007,...,2.018000e+03,2.019000e+03,2.020000e+03,2.021000e+03,2.022000e+03,2.023000e+03,2.024000e+03,2.025000e+03,2.026000e+03,NO ANO 2026 / 2025 (%) ¹
32,NaN,Janeiro,35794008.857865,40873730.614515,44701019.302848,46606186.335444,45176780.46835,46432973.773778,52339783.845583,53824796.350434,...,8.107100e+07,8.155870e+07,9.822063e+07,8.906345e+07,9.400690e+07,1.015059e+08,1.090928e+08,1.069080e+08,1.225556e+08,14.636505
33,NaN,Fevereiro,32501396.224157,37557965.0644,40186194.879912,43224390.926032,42107534.900961,41792056.208912,47384033.111868,49231395.381646,...,7.328567e+07,6.970387e+07,8.617864e+07,7.892984e+07,8.166354e+07,9.132366e+07,1.000015e+08,9.766675e+07,1.137095e+08,16.426035
34,NaN,Março,36867745.46787,39067393.6682,45154999.548199,46879152.013009,45882541.17902,47688719.873715,52570652.717971,54842114.434007,...,7.927629e+07,7.936296e+07,9.217495e+07,8.817393e+07,9.241669e+07,9.657611e+07,1.040439e+08,1.122451e+08,1.316677e+08,16.133116
35,NaN,Abril,34837415.933632,38071024.8661,44078493.346157,45602466.821091,43472197.92968,50287471.991477,52117983.759629,52171323.61276,...,7.790183e+07,7.811707e+07,8.875093e+07,8.922370e+07,8.997322e+07,9.423560e+07,9.583257e+07,1.089629e+08,NaN,NaN
36,NaN,Maio,35934804.682263,37238989.92987,45952929.184768,46118339.488721,44039672.135652,52360679.34918,54191399.693721,53502031.039296,...,8.083113e+07,8.466005e+07,8.572848e+07,9.088427e+07,8.924257e+07,9.924005e+07,1.028559e+08,1.140513e+08,NaN,NaN
37,NaN,Junho,36257689.1853,38829947.05089,45077503.994253,41168093.408024,44447747.46068,50952058.85111,48913004.784319,53511523.840692,...,7.769535e+07,7.672296e+07,9.039438e+07,8.710311e+07,8.485649e+07,1.009971e+08,1.023500e+08,1.127254e+08,NaN,NaN
38,NaN,Julho,36802876.455907,40431678.61644,45064784.488879,46224419.650295,46915428.61798,52094156.2611,53480760.914616,54988932.984202,...,7.982900e+07,8.601576e+07,9.542745e+07,9.440305e+07,9.183831e+07,1.088944e+08,1.002047e+08,1.227264e+08,NaN,NaN
39,NaN,Agosto,36962797.139489,39864973.02525,46630629.66927,47772193.388881,46565206.399249,50400788.45366,52790965.754465,54511169.004821,...,7.817412e+07,9.267234e+07,9.569693e+07,9.291758e+07,9.568530e+07,1.073235e+08,1.036224e+08,1.207784e+08,NaN,NaN

Podemos fazer dessa forma para identificar apenas onde estão os dados

In [10]:
for i, row in raw.iterrows():
    if row.notna().sum() > 5:
        print(i)

29
31
32
33
34
35
36
37
38
39
40
41
42
43
44
93
95
96
97
98
99
100
101
102
103
104
105
106
107
108

Perceba o salto de 44 para 93, da pra entender que temos nessa mesma planilha duas tabelas  

Extraindo apenas a primeira tabela

In [11]:
petroleo = raw.iloc[31:45].copy()

petroleo.head()

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
31,NaN,Mês,2000,2001,2002,2003,2004,2005,2006,2007,...,2.018000e+03,2.019000e+03,2.020000e+03,2.021000e+03,2.022000e+03,2.023000e+03,2.024000e+03,2.025000e+03,2.026000e+03,NO ANO 2026 / 2025 (%) ¹
32,NaN,Janeiro,35794008.857865,40873730.614515,44701019.302848,46606186.335444,45176780.46835,46432973.773778,52339783.845583,53824796.350434,...,8.107100e+07,8.155870e+07,9.822063e+07,8.906345e+07,9.400690e+07,1.015059e+08,1.090928e+08,1.069080e+08,1.225556e+08,14.636505
33,NaN,Fevereiro,32501396.224157,37557965.0644,40186194.879912,43224390.926032,42107534.900961,41792056.208912,47384033.111868,49231395.381646,...,7.328567e+07,6.970387e+07,8.617864e+07,7.892984e+07,8.166354e+07,9.132366e+07,1.000015e+08,9.766675e+07,1.137095e+08,16.426035
34,NaN,Março,36867745.46787,39067393.6682,45154999.548199,46879152.013009,45882541.17902,47688719.873715,52570652.717971,54842114.434007,...,7.927629e+07,7.936296e+07,9.217495e+07,8.817393e+07,9.241669e+07,9.657611e+07,1.040439e+08,1.122451e+08,1.316677e+08,16.133116
35,NaN,Abril,34837415.933632,38071024.8661,44078493.346157,45602466.821091,43472197.92968,50287471.991477,52117983.759629,52171323.61276,...,7.790183e+07,7.811707e+07,8.875093e+07,8.922370e+07,8.997322e+07,9.423560e+07,9.583257e+07,1.089629e+08,NaN,NaN

transformando agora a primeira linha em cabeçalho

In [12]:
petroleo.columns = petroleo.iloc[0]

petroleo = petroleo.iloc[1:]

petroleo.head()

31,NaN,Mês,2000,2001,2002,2003,2004,2005,2006,2007,...,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0,2025.0,2026.0,NO ANO 2026 / 2025 (%) ¹
32,NaN,Janeiro,35794008.857865,40873730.614515,44701019.302848,46606186.335444,45176780.46835,46432973.773778,52339783.845583,53824796.350434,...,8.107100e+07,8.155870e+07,9.822063e+07,8.906345e+07,9.400690e+07,1.015059e+08,1.090928e+08,1.069080e+08,1.225556e+08,14.636505
33,NaN,Fevereiro,32501396.224157,37557965.0644,40186194.879912,43224390.926032,42107534.900961,41792056.208912,47384033.111868,49231395.381646,...,7.328567e+07,6.970387e+07,8.617864e+07,7.892984e+07,8.166354e+07,9.132366e+07,1.000015e+08,9.766675e+07,1.137095e+08,16.426035
34,NaN,Março,36867745.46787,39067393.6682,45154999.548199,46879152.013009,45882541.17902,47688719.873715,52570652.717971,54842114.434007,...,7.927629e+07,7.936296e+07,9.217495e+07,8.817393e+07,9.241669e+07,9.657611e+07,1.040439e+08,1.122451e+08,1.316677e+08,16.133116
35,NaN,Abril,34837415.933632,38071024.8661,44078493.346157,45602466.821091,43472197.92968,50287471.991477,52117983.759629,52171323.61276,...,7.790183e+07,7.811707e+07,8.875093e+07,8.922370e+07,8.997322e+07,9.423560e+07,9.583257e+07,1.089629e+08,NaN,NaN
36,NaN,Maio,35934804.682263,37238989.92987,45952929.184768,46118339.488721,44039672.135652,52360679.34918,54191399.693721,53502031.039296,...,8.083113e+07,8.466005e+07,8.572848e+07,9.088427e+07,8.924257e+07,9.924005e+07,1.028559e+08,1.140513e+08,NaN,NaN

In [13]:
## verificando os tipos

petroleo.info()

<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 32 to 44
Data columns (total 30 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   nan                       0 non-null      float64
 1   Mês                       13 non-null     str
 2   2000                      13 non-null     object
 3   2001                      13 non-null     object
 4   2002                      13 non-null     object
 5   2003                      13 non-null     object
 6   2004                      13 non-null     object
 7   2005                      13 non-null     object
 8   2006                      13 non-null     object
 9   2007                      13 non-null     object
 10  2008.0                    13 non-null     float64
 11  2009.0                    13 non-null     float64
 12  2010.0                    13 non-null     float64
 13  2011.0                    13 non-null     float64
 14  2012.0                    13 non-null     float64
 15  2013.0                    13 non-null     float64
 16  2014.0                    13 non-null     float64
 17  2015.0                    13 non-null     float64
 18  2016.0                    13 non-null     float64
 19  2017.0                    13 non-null     float64
 20  2018.0                    13 non-null     float64
 21  2019.0                    13 non-null     float64
 22  2020.0                    13 non-null     float64
 23  2021.0                    13 non-null     float64
 24  2022.0                    13 non-null     float64
 25  2023.0                    13 non-null     float64
 26  2024.0                    13 non-null     float64
 27  2025.0                    13 non-null     float64
 28  2026.0                    4 non-null      float64
 29  NO ANO 2026 / 2025 (%) ¹  3 non-null      object
dtypes: float64(20), object(9), str(1)
memory usage: 3.2+ KB

### Exploração inicial agora

vendo se há agora nessa "nova" tabela petroleo, valores faltantes

In [14]:
petroleo.isna().sum()

31
NaN                         13
Mês                          0
2000                         0
2001                         0
2002                         0
2003                         0
2004                         0
2005                         0
2006                         0
2007                         0
2008.0                       0
2009.0                       0
2010.0                       0
2011.0                       0
2012.0                       0
2013.0                       0
2014.0                       0
2015.0                       0
2016.0                       0
2017.0                       0
2018.0                       0
2019.0                       0
2020.0                       0
2021.0                       0
2022.0                       0
2023.0                       0
2024.0                       0
2025.0                       0
2026.0                       9
NO ANO 2026 / 2025 (%) ¹    10
dtype: int64

Fazendo um resumo estatístico

In [15]:
petroleo.describe()

31,NaN,2008.0,2009.0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0,2025.0,2026.0
count,0.0,1.300000e+01,1.300000e+01,1.300000e+01,1.300000e+01,1.300000e+01,1.300000e+01,1.300000e+01,1.300000e+01,1.300000e+01,1.300000e+01,1.300000e+01,1.300000e+01,1.300000e+01,1.300000e+01,1.300000e+01,1.300000e+01,1.300000e+01,1.300000e+01,4.000000e+00
mean,NaN,1.020422e+08,1.095202e+08,1.153773e+08,1.182260e+08,1.160626e+08,1.136482e+08,1.266043e+08,1.368716e+08,1.413432e+08,1.472196e+08,1.452488e+08,1.565433e+08,1.655418e+08,1.631337e+08,1.696692e+08,1.910142e+08,1.890787e+08,2.117024e+08,1.839664e+08
std,NaN,1.686369e+08,1.810002e+08,1.906835e+08,1.953899e+08,1.918178e+08,1.878287e+08,2.092766e+08,2.262075e+08,2.336346e+08,2.432983e+08,2.400459e+08,2.588068e+08,2.736048e+08,2.696121e+08,2.804272e+08,3.157312e+08,3.124782e+08,3.499315e+08,1.228632e+08
min,NaN,5.138150e+07,5.342310e+07,5.646453e+07,5.773994e+07,5.771041e+07,5.648437e+07,5.851143e+07,6.807800e+07,6.771561e+07,7.491401e+07,7.328567e+07,6.970387e+07,8.263747e+07,7.892984e+07,8.166354e+07,9.132366e+07,9.583257e+07,9.766675e+07,1.137095e+08
25%,NaN,5.424653e+07,5.856229e+07,6.189823e+07,6.361348e+07,6.134343e+07,6.120790e+07,6.567806e+07,7.185965e+07,7.294399e+07,7.904897e+07,7.769535e+07,7.936296e+07,8.617864e+07,8.710311e+07,8.997322e+07,9.924005e+07,1.002047e+08,1.122451e+08,1.203441e+08
50%,NaN,5.571431e+07,5.978423e+07,6.267087e+07,6.438333e+07,6.272056e+07,6.243336e+07,7.028580e+07,7.477491e+07,7.825575e+07,8.024309e+07,7.927629e+07,8.601576e+07,8.908118e+07,8.906345e+07,9.286443e+07,1.073235e+08,1.028559e+08,1.140513e+08,1.271117e+08
75%,NaN,5.681295e+07,6.076903e+07,6.433129e+07,6.565390e+07,6.470701e+07,6.366126e+07,7.211580e+07,7.655332e+07,8.087101e+07,8.145025e+07,8.103809e+07,9.267234e+07,9.542745e+07,9.088427e+07,9.528673e+07,1.101673e+08,1.041745e+08,1.227264e+08,1.907340e+08
max,NaN,6.632741e+08,7.118815e+08,7.499524e+08,7.684693e+08,7.544072e+08,7.387131e+08,8.229280e+08,8.896656e+08,9.187310e+08,9.569277e+08,9.441174e+08,1.017531e+09,1.076022e+09,1.060369e+09,1.102850e+09,1.241592e+09,1.229012e+09,1.376065e+09,3.679328e+08

Acontece que agora os dados estão nesse formato de Mês | 2000 | 2001 | 2002 | ... mas da pra fazer uma análise melhor se converter para o formato de tidy data. vamos em outras palavras, alinhar Mẽs | ano | produção

In [16]:
print(petroleo.columns.tolist())

[np.float64(nan), 'Mês', 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, np.float64(2008.0), np.float64(2009.0), np.float64(2010.0), np.float64(2011.0), np.float64(2012.0), np.float64(2013.0), np.float64(2014.0), np.float64(2015.0), np.float64(2016.0), np.float64(2017.0), np.float64(2018.0), np.float64(2019.0), np.float64(2020.0), np.float64(2021.0), np.float64(2022.0), np.float64(2023.0), np.float64(2024.0), np.float64(2025.0), np.float64(2026.0), 'NO ANO 2026 / 2025 (%) ¹']

In [17]:
petroleo_long = pd.melt(
    petroleo,
    id_vars="Mês",
    var_name="Ano",
    value_name="Produção"
)

petroleo_long.head()

         Mês  Ano Produção
0    Janeiro  NaN      NaN
1  Fevereiro  NaN      NaN
2      Março  NaN      NaN
3      Abril  NaN      NaN
4       Maio  NaN      NaN